import type { Config } from "tailwindcss";

// Design tokens for the dark quant-terminal theme
const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#31353c",
        error: "#ffb4ab",
        "on-tertiary-fixed-variant": "#930005",
        "tertiary-fixed": "#ffdad5",
        "outline-variant": "#30363D",
        background: "#000000",
        "surface-container": "#0D1117",
        "secondary-fixed-dim": "#3ce42f",
        "on-surface": "#dfe2eb",
        "inverse-surface": "#dfe2eb",
        "on-secondary-fixed": "#002200",
        "on-error-container": "#ffdad6",
        "surface-bright": "#353940",
        "inverse-primary": "#7c5800",
        "secondary-container": "#00c705",
        "on-primary-fixed": "#271900",
        "on-tertiary": "#690003",
        "surface-dim": "#10141a",
        "on-primary-fixed-variant": "#5e4200",
        "on-primary-container": "#6b4c00",
        "primary-fixed": "#ffdea8",
        "on-tertiary-container": "#a70007",
        "surface-variant": "#31353c",
        "on-secondary": "#003a00",
        "primary-fixed-dim": "#ffba20",
        "surface-container-high": "#161B22",
        "on-error": "#690005",
        "on-secondary-container": "#004b00",
        "on-tertiary-fixed": "#410001",
        "tertiary-container": "#ffb1a7",
        "on-primary": "#412d00",
        "on-background": "#dfe2eb",
        surface: "#000000",
        "inverse-on-surface": "#2d3137",
        outline: "#484F58",
        "surface-tint": "#ffba20",
        tertiary: "#ffd8d2",
        "primary-container": "#FFB800",
        "surface-container-low": "#0D1117",
        "on-surface-variant": "#d5c4ab",
        "error-container": "#93000a",
        primary: "#ffdca1",
        "secondary-fixed": "#77ff62",
        "surface-container-lowest": "#0a0e14",
        secondary: "#3ce42f",
        "on-secondary-fixed-variant": "#005300",
        "tertiary-fixed-dim": "#ffb4aa",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        gutter: "1px",
        unit: "4px",
        "panel-padding": "12px",
        "container-gap": "8px",
      },
      fontFamily: {
        "data-lg": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "data-md": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "data-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      // Slightly reduced scale — denser terminal, less cramped spacing per element.
      fontSize: {
        "data-lg": ["16px", { lineHeight: "22px", fontWeight: "500" }],
        "data-md": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "display-lg": [
          "21px",
          { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "data-sm": ["10px", { lineHeight: "13px", fontWeight: "400" }],
        "headline-md": ["16px", { lineHeight: "22px", fontWeight: "600" }],
        "label-caps": [
          "9px",
          { lineHeight: "11px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
